shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('greetings/', views.greeting),
    path('', views.list_item, name='list_item'),
    path('<int:item_id>/', views.detail_item, name='detail_item'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
]

shop/models.py
from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField()

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'



    def __str__(self):
        return self.name

class Purchase(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    data_purchase = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'



    def __str__(self):
        return f'{self.name} {self.age} {self.name}'

shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


from .models import Item, Purchase

def greeting(request):
    return HttpResponse('Добро пожаловать в наш магазин')


def list_item(request):
    items = Item.objects.all()
    context = {
        'items': items,
    }
    return render(request, 'list_item.html', context)

def detail_item(request, item_id):
    item = Item.objects.get(name=item_id)
    context = {
        'item': item
    }
    return render(request, 'detail_item.html', context)

shop/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


  </head>
  <body>


 <div class="container mb-5 mt-5">

     {% block content %}
     {% endblock content %}

 </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>


  </body>
</html>

shop/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<form  method="POST" action="{% url item.name %}">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ item.name }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for purchase in item.purchase_set.all %}
        <label for="purchase{{ forloop.counter }}">{{ purchase.name }}</label><br>
    {% endfor %}
</fieldset>
</form>

{% endblock content %}

shop/templates/list_item.html
{% extends 'base.html' %}

{% block content %}

<ul>
    {% for item in items %}
    <li> <a href="{% url 'detail_item' item.id %}">{{ item.name }}</a></li>
    {% endfor %}
</ul>

{%endblock content %}